# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

minimax_alt <- function(design_type, pso_info, design_info_list, init_bound_info, nelder_mead_settings, n_threads, verbose) {
    .Call(`_minimaxALT_minimax_alt`, design_type, pso_info, design_info_list, init_bound_info, nelder_mead_settings, n_threads, verbose)
}

transform_proportion <- function(dirichlet_prop) {
    .Call(`_minimaxALT_transform_proportion`, dirichlet_prop)
}

transform_sigmoid <- function(inbound_sigmoid, lower_bound, upper_bound) {
    .Call(`_minimaxALT_transform_sigmoid`, inbound_sigmoid, lower_bound, upper_bound)
}

equivalence_theorem <- function(alloc, design_info_list, model_set_in) {
    .Call(`_minimaxALT_equivalence_theorem`, alloc, design_info_list, model_set_in)
}

